@echo off
echo Starting My Word Backend Server...
cd backend
if not exist node_modules (
    echo Installing dependencies...
    call npm install
)
echo seeding database...
call node seed.js
echo Starting Server...
call npm start
pause
